baseURL = "https://jeromerodrigo.xyz/"
languageCode = "en"
title = "Jerome Rodrigo | Full Stack Software Developer"

[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2

[params]
    description = """\
    The personal site & blog of jeromerodrigo.\
    """

    dateFormat = "Jan 2, 2006"

    nameLower = "jeromerodrigo"

    footerLine = "Made with ❤️ by [@jeromerodrigo](https://github.com/jeromerodrigo)"
    footerCopyright = "Jerome Rodrigo."

    linkedinUrl = "https://www.linkedin.com/in/jeromerodrigo"

[taxonomies]
    tag = "tags"