baseURL = "https://jeromerodrigo.com/"
languageCode = "en"
title = "Jerome Rodrigo · Full Stack Software Developer"

[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "About"
        pre = "about"
        url = "/about/"
        weight = 2

    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 3

[params]
    description = "Personal site & blog of jeromerodrigo."
    images = ["img/profile.webp"]

    dateFormat = "Jan 2, 2006"

    nameLower = "jeromerodrigo"

    footerLine = "Made with ❤️ by Jerome."
    footerCopyright = "Jerome Rodrigo"

    linkedinUrl = "https://www.linkedin.com/in/jeromerodrigo"

    titlePostfix = "· Jerome Rodrigo"

[taxonomies]
    tag = "tags"